services:
  - type: web
    name: hr-system-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://hr-system-7ue8.onrender.com/api